#!/bin/bash

cp .env.example .env

source .env

composer install

./vendor/bin/sail up -d

./vendor/bin/sail artisan key:generate
./vendor/bin/sail artisan passport:keys

./vendor/bin/sail artisan migrate:refresh --seed

./vendor/bin/sail artisan test

echo "API is running on http://localhost:$APP_PORT"
